### ISSUE TITLE
Avoid installing plugin twice

### ISSUE THREAD

**Issue by desyncr** [zpm-project/zpm-zsh#1]
If a user tries to install a plugin twice we should

1) warn the user the plugin in already installed
2) return immediately

Migrated from: https://github.com/desyncr/zpm-zsh/issues/27

**Comment by fennecdjay** [comment]
Wouldn't a plugin_entry_exists() function, checking .plugin_list for the entry do the job?

```c
    } else {
        if (plugin_entry_exists()) {
            zpm_message(ZPM_ERROR, "plugin \"%s\" already installed.\n", plugin_name);
            return 1;
        }
        plugin_name = malloc(PATH_MAX);
        strcpy(plugin_name, plugin_name_or_command);
    }
int status = strstr(plugin_name, "/") ? 0 : -1; ...

```

**Comment by fennecdjay** [comment]
see #14.

**Comment by fennecdjay** [comment]
You can probably close this too.

**Comment by desyncr** [comment]
Oh, yeah. Moving really fast, which is great! :D
