### ISSUE TITLE
Review multi-host support

### ISSUE THREAD

**Issue by desyncr** [zpm-project/zpm-zsh#3]
- Review implementation to be fully host agnostic (github, bitbucket, etc)
- Avoid hardcoding hosts (try to...)
- Add tests

@fennecdjay I have yet no idea how to implement this so any suggestion is welcome!

We should discuss here before doing any PR :)

### TODO

  - [x] Using "https://" causes plugin install to fail
  - [x] It does creates "\<hostname\>/user/repo.git" folders

**Comment by fennecdjay** [comment]
Maybe we could have
```c
#define ZPM_DEFAULT_HOST "github.com"
```
in *config.h* then
```c
if (!(host = getenv(ZPM_DEFAULT_HOST)) {
    host = ZPM_DEFAULT_VALUE;
}
```
-------
I can give it a try tomorrow if you want.

**Comment by desyncr** [comment]
Done in #28
