### ISSUE TITLE
Add to homebrew

### ISSUE THREAD

**Issue by jedahan** [zpm-project/zpm-zsh#35]
Feel free to assign to me. Would be nice to have in homebrew.

**Comment by desyncr** [comment]
It would be really cool! @fennecdjay maintains [AUR](https://aur.archlinux.org/packages/zpm-zsh/) having homebrew would be a really cool addition!

We should update the README as well.

**Comment by desyncr** [comment]
@jedahan I guess `zpm` is not cool enough! Yet!

**Comment by jedahan** [comment]
I can create a tap tonight or tomorrow, and if you want you can fork it to `zpm-project/homebrew`, and I'll add it to the readme.

**Comment by desyncr** [comment]
That would be really cool! Yes, please go ahead!

**Comment by fennecdjay** [comment]
see #39.

**Comment by jedahan** [comment]
I don't use zpm-zsh anymore so I'm gonna close this

**Comment by jedahan** [comment]
Please unassign me if you do reopen :)
